FROM node:24-alpine
WORKDIR /usr/app

COPY package.json tsconfig.json ./
RUN npm install

COPY src src
COPY testservicecommon testservicecommon
COPY testbookservice testservice

ENTRYPOINT [ "npm" ]
CMD [ "start" ]
