version: '3'
services:
  bookservice:
    ports: 
      - 81:80
  basicbookservice:
    ports: 
      - 82:80
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.apollo
    # logging:
    #   driver: none
    ports:
      - 80:80
    depends_on:
      - bookservice
      - libraryservice
  libraryservice:
    ports: 
      - 83:80
